### ISSUE TITLE
What is passed to Home Assistant?

### ISSUE THREAD

**Issue by crxporter** [teharris1/python-insteonplm#3]
I’m on the line getting ready to buy a PLM to replace my terrible “insteon pro hub” - I’m wondering if this setup with home assistant can recognize a double click on my switches to set a scene separate from just turning off that switch? I believe this is possible with the regular Insteon Hub...

**Comment by teharris1** [comment]
Currently no. A double tap is recognized as a FAST ON or a FAST OFF in the current version. It is in the roadmap for this library to raise events such as double taps. The problem is HA does not really recognize events from devices. It recognizes state changes. To make this work I need to extend the HA entity to see an event. Not easy.

**Comment by crxporter** [comment]
Thanks for the response! I've gone through a lot of the HA forums and seen that you've been hard at work on this project - I appreciate it! I'm going to give this plugin a try (ordered my PLM today) with a hope that someday I might get double tap "buttons" passed through HA to HomeKit so I can have another level of options.

**Comment by crxporter** [comment]
While I've got this open I'm going to throw one more question in - I got my PLM this afternoon and I've got my switches working pretty well. One thing that isn't quite right is when I turn my dimmers "on" at the wall - HA shows "0% brightness" but "on". 

Please be patient with me, it's my second day with HA.

**Comment by teharris1** [comment]
Yeah, that is an HA issue, not Insteon specific.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by crxporter** [comment]
I actually figured this out and deleted the question - I was able to "trick" HA into thinking the "on" button press was 100% by putting "brightness: 256" in my customize.yaml file. Of course that only works for on-level of 100% but I'm happier seeing that than "0%" every time.

For reference here's my deleted question:

> While I've got this open I'm going to throw one more question in - I got my PLM this afternoon and I've got my switches working pretty well. One thing that isn't quite right is when I turn my dimmers "on" at the wall - HA shows "0% brightness" but "on".
> 
> Please be patient with me, it's my second day with HA.

**Comment by teharris1** [comment]
Didn't know about that option. Good to know.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by crxporter** [comment]
I'm glad I could contribute. I plan to set the devices that I turn on "dim" to "brightness: 64" so they'll start up and show 25%. Seems to work well.

Last question for the night: do everyone's PLM setups only turn on one light at a time - then go to the next? I set up a group and a scene, the lights turn on sequentially instead of all at once. What's the standard approach to deal with that? I don't know that I want my scenes involving 6 or 7 switches to take 15 seconds before the automation is through changing them all...

**Comment by crxporter** [comment]
I'd be very interested to know if theres anything I can do to speed that up. I haven't written code in a long time and the Insteon stuff seems pretty complicated - but I'd be a happy guinea pig to test new features. 

Or if anyone out there takes bribes...
